### ISSUE TITLE
Hello This is not an Issue but a Query

### ISSUE THREAD

**Issue by rakshitsukanta** [mehrdadbahri/export_woocommerce_for_odoo#1]
I have two questions.
1. These bash scripts are compatible with which version of Odoo?
2. Can you give some details on these steps? Please forgive me I am a newbie in this field :(

Set the created config file path in the environment variable mysql_connection_config_path:
export mysql_connection_config_path=~/mysql_connection.conf

and this step:

Turn off sql_mode=only_full_group_by option for mysql:

SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));

**Comment by mehrdadbahri** [comment]
1. I have tested with Odoo version 14.
2.
You should first create a file containing the database connection information and set the file path in an environment variable named mysql_connection_config_path. Just executed the given command and change the path if needed.

Just open a MySQL shell and execute the query.
